FROM python:3.13-slim

ARG PYLONTECH_BUILD_VERSION=""
ARG PYLONTECH_BUILD_REVISION=development

ENV PYLONTECH_BUILD_VERSION=${PYLONTECH_BUILD_VERSION}
ENV PYLONTECH_BUILD_REVISION=${PYLONTECH_BUILD_REVISION}

WORKDIR /app

COPY . .
RUN python -m pip install --no-cache-dir .

CMD ["python", "-m", "pylontech_console.main"]
